#!/bin/sh
if [ "$(id -u)" -ne 0 ]; then
        echo 'This script must be run by root' >&2
        exit 1
fi
cd /tmp \
&& wget -N https://git.launchpad.net/linux-purge/plain/install-linux-purge.sh \
&& chmod +x ./install-linux-purge.sh \
&& ./install-linux-purge.sh \
&& rm ./install-linux-purge.sh \
|| { err=$?; echo 'Error: Updating linux-purge failed' >&2; exit $err; }
echo 'Note: Bash completion might not work before you run bash again (e.g. by "exec bash").'
